# Generated by Django 2.2 on 2020-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата добавления')),
                ('title', models.CharField(max_length=255, verbose_name='Дата добавления')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('vendor', models.CharField(max_length=255, verbose_name='Поставщик')),
                ('unit_of_measure', models.CharField(max_length=30, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
