# Generated by Django 2.2 on 2020-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooditem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
